#!/bin/bash
# takes in 3 arguments: protein AA filename, genome accession, output directory

echo $1
docker run --rm \
  -v $PWD/interproscan-5.74-105.0/data:/opt/interproscan/data \
  -v $PWD:/work \
  interpro/interproscan:5.74-105.0 \
  --cpu 4 \
  --appl Pfam \
  --input /work/$1 \
  --output-file-base /work/$3/$2
